<?php

return [
    'categories' => [
        'len-soi' => [
            'slug'  => 'len-soi',
            'name'  => 'Len sợi',
            'tag'   => 'Chất liệu đa dạng',
            'desc'  => 'Bộ sưu tập len cotton, mohair, acrylic, wool... màu pastel được chọn lọc tỉ mỉ cho mọi dự án handmade.',
            'image' => '/images/2.jpg',
            'icon'  => 'yarn',
        ],
        'kim-moc' => [
            'slug'  => 'kim-moc',
            'name'  => 'Kim & Móc',
            'tag'   => 'Dụng cụ chuyên dụng',
            'desc'  => 'Kim đan inox, móc ergonomic, đầu khoá, kim chặn... đầy đủ size cho từng loại len và cấp độ kỹ năng.',
            'image' => '/images/4.jpg',
            'icon'  => 'hook',
        ],
        'starter-kit' => [
            'slug'  => 'starter-kit',
            'name'  => 'Starter Kit',
            'tag'   => 'Combo cho người mới',
            'desc'  => 'Bộ kit đầy đủ len, kim, mắt thú, hướng dẫn — bắt đầu hành trình handmade trong 15 phút.',
            'image' => '/images/5.jpg',
            'icon'  => 'box',
        ],
        'phu-kien' => [
            'slug'  => 'phu-kien',
            'name'  => 'Phụ kiện handmade',
            'tag'   => 'Nhỏ xinh mà chất',
            'desc'  => 'Mắt thú, khoá túi, dây viền, sticker, túi đựng len... giúp sản phẩm cuối thêm chỉn chu.',
            'image' => '/images/6.jpg',
            'icon'  => 'sparkle',
        ],
    ],

    'products' => [
        'len-soi' => [
            [
                'slug'      => 'len-cotton-pastel',
                'name'      => 'Len Cotton Mềm Mại Pastel',
                'tag'       => 'Bán chạy',
                'price'     => 85000,
                'oldPrice'  => 105000,
                'image'     => '/images/2.jpg',
                'shortDesc' => 'Len cotton 100% tự nhiên, màu pastel nhẹ nhàng, phù hợp đan áo và thú bông mùa hè.',
                'desc'      => 'Cuộn 50g với chất cotton tinh khiết, không phai màu, không xù sau giặt. Sợi đều tay, thích hợp cho cả người mới và thợ lâu năm. Có 12 tone pastel thời thượng, phối màu dễ dàng.',
                'features'  => ['Cotton 100% organic', 'Không xù sau khi giặt', 'Độ ẩm thấm tốt', 'An toàn cho da nhạy cảm'],
                'variants'  => [
                    ['label' => 'Hồng phấn',   'color' => '#f9c3d9', 'stock' => 25],
                    ['label' => 'Hồng đào',    'color' => '#f6a8a8', 'stock' => 18],
                    ['label' => 'Hồng nude',   'color' => '#ffd1dc', 'stock' => 22],
                    ['label' => 'Xanh mint',   'color' => '#c3e8d5', 'stock' => 18],
                    ['label' => 'Xanh ngọc',   'color' => '#a8d5d5', 'stock' => 16],
                    ['label' => 'Vàng kem',    'color' => '#fbe8a9', 'stock' => 22],
                    ['label' => 'Vàng bơ',     'color' => '#fef5d7', 'stock' => 20],
                    ['label' => 'Tím oải',     'color' => '#d9c3e8', 'stock' => 15],
                    ['label' => 'Tím lavender','color' => '#c5a8e0', 'stock' => 12],
                    ['label' => 'Xanh baby',   'color' => '#a8d5f6', 'stock' => 14],
                    ['label' => 'Trắng ngà',   'color' => '#f5ede0', 'stock' => 30],
                    ['label' => 'Cam đào',     'color' => '#ffbfa3', 'stock' => 17],
                ],
                'sizes'     => ['50g', '100g'],
            ],
            [
                'slug'      => 'len-gradient-ombre',
                'name'      => 'Len Sợi Gradient Ombre',
                'tag'       => 'Mới',
                'price'     => 120000,
                'oldPrice'  => null,
                'image'     => '/images/3.jpg',
                'shortDesc' => 'Cuộn len chuyển màu tự nhiên, tạo hiệu ứng ombre đẹp mắt mà không cần đổi chỉ.',
                'desc'      => 'Công nghệ nhuộm gradient Hàn Quốc giúp sợi len chuyển màu mượt mà trong suốt cuộn. Thích hợp đan khăn, áo len và túi tote với hiệu ứng nghệ thuật.',
                'features'  => ['Chuyển màu tự nhiên', 'Kỹ thuật nhuộm cao cấp', 'Không đổi chỉ khi đan', 'Cuộn 100g — móc được 1 khăn'],
                'variants'  => [
                    ['label' => 'Hoàng hôn',    'color' => 'linear-gradient(135deg,#f6a8c5,#fbe8a9)', 'stock' => 12],
                    ['label' => 'Đại dương',    'color' => 'linear-gradient(135deg,#a8d5f6,#c3e8d5)', 'stock' => 14],
                    ['label' => 'Bình minh',    'color' => 'linear-gradient(135deg,#fbe8a9,#f9c3d9)', 'stock' => 8],
                    ['label' => 'Rừng mơ',      'color' => 'linear-gradient(135deg,#c3e8d5,#d9c3e8)', 'stock' => 10],
                    ['label' => 'Candy',        'color' => 'linear-gradient(135deg,#f9c3d9,#d9c3e8)', 'stock' => 11],
                    ['label' => 'Tropical',     'color' => 'linear-gradient(135deg,#ff9a70,#f6a8c5)', 'stock' => 9],
                    ['label' => 'Galaxy',       'color' => 'linear-gradient(135deg,#2c3e60,#c5a8e0)', 'stock' => 7],
                    ['label' => 'Mây chiều',    'color' => 'linear-gradient(135deg,#d9c3e8,#ffd1dc)', 'stock' => 13],
                ],
                'sizes'     => ['100g', '200g'],
            ],
            [
                'slug'      => 'len-mohair-anh-kim',
                'name'      => 'Len Mohair Mỏng Ánh Kim',
                'tag'       => 'Hot',
                'price'     => 145000,
                'oldPrice'  => null,
                'image'     => '/images/1.jpg',
                'shortDesc' => 'Len mohair siêu nhẹ, ánh lấp lánh tinh tế — lý tưởng để layer cùng len khác.',
                'desc'      => 'Mohair pha kid (78% mohair, 22% silk) tạo cảm giác bông và mềm. Sợi mảnh 2.5mm thích hợp móc khăn mỏng, áo layer, váy baby doll.',
                'features'  => ['Pha silk cao cấp', 'Ánh kim tự nhiên', 'Siêu nhẹ, ấm', 'Không ngứa'],
                'variants'  => [
                    ['label' => 'Hồng ánh kim',  'color' => '#f6a8c5', 'stock' => 10],
                    ['label' => 'Hồng nhung',    'color' => '#e85c8f', 'stock' => 8],
                    ['label' => 'Xanh ngọc',     'color' => '#a8d5d5', 'stock' => 8],
                    ['label' => 'Xanh pastel',   'color' => '#b8d9f0', 'stock' => 9],
                    ['label' => 'Bạc',           'color' => '#e5e5ed', 'stock' => 12],
                    ['label' => 'Vàng champagne','color' => '#e8d5a8', 'stock' => 7],
                    ['label' => 'Tím khói',      'color' => '#b8a0c8', 'stock' => 6],
                    ['label' => 'Đen huyền',     'color' => '#2a2a33', 'stock' => 6],
                    ['label' => 'Trắng tuyết',   'color' => '#fafafa', 'stock' => 11],
                ],
                'sizes'     => ['25g', '50g'],
            ],
            [
                'slug'      => 'len-wool-am-ap',
                'name'      => 'Len Wool Ấm Áp Mùa Đông',
                'tag'       => 'Hot',
                'price'     => 165000,
                'oldPrice'  => 195000,
                'image'     => '/images/6.jpg',
                'shortDesc' => 'Len wool merino mềm, ấm — chuyên dành cho áo len và khăn mùa đông.',
                'desc'      => 'Merino wool nhập từ Úc, không ngứa, giữ nhiệt tốt. Sợi 4mm chuẩn để đan áo len cao cấp. Cuộn 100g đủ cho 1 nửa áo người lớn.',
                'features'  => ['Merino Wool 100%', 'Nhập khẩu Úc', 'Không ngứa, không dị ứng', 'Giữ nhiệt vượt trội'],
                'variants'  => [
                    ['label' => 'Cam đất',       'color' => '#d89878', 'stock' => 14],
                    ['label' => 'Cam gạch',      'color' => '#c06850', 'stock' => 10],
                    ['label' => 'Đỏ burgundy',   'color' => '#8f4756', 'stock' => 9],
                    ['label' => 'Đỏ rượu vang',  'color' => '#6b2e3e', 'stock' => 8],
                    ['label' => 'Xám tro',       'color' => '#9fa0a5', 'stock' => 16],
                    ['label' => 'Xám khói',      'color' => '#6a6b72', 'stock' => 13],
                    ['label' => 'Xanh navy',     'color' => '#2c3e60', 'stock' => 11],
                    ['label' => 'Xanh rêu',      'color' => '#5a7055', 'stock' => 9],
                    ['label' => 'Nâu cacao',     'color' => '#6a4a3a', 'stock' => 10],
                    ['label' => 'Đen',           'color' => '#1a1a20', 'stock' => 14],
                    ['label' => 'Trắng kem',     'color' => '#f5ede0', 'stock' => 18],
                ],
                'sizes'     => ['100g', '200g'],
            ],
            [
                'slug'      => 'len-acrylic-mem-mai',
                'name'      => 'Len Acrylic Mềm Tiết Kiệm',
                'tag'       => 'Sale',
                'price'     => 45000,
                'oldPrice'  => 65000,
                'image'     => '/images/5.jpg',
                'shortDesc' => 'Len acrylic mềm, đa năng — lựa chọn tốt cho người mới tập đan móc.',
                'desc'      => 'Acrylic chất lượng cao, mềm tay, dễ giặt máy. Rẻ nhưng không hề rẻ tiền — cuộn 100g sợi đều, không rối, phù hợp làm thú bông và túi tote.',
                'features'  => ['Giá hợp lý', 'Giặt máy OK', 'Dễ thao tác', '15+ màu có sẵn'],
                'variants'  => [
                    ['label' => 'Hồng baby',    'color' => '#ffd1dc', 'stock' => 35],
                    ['label' => 'Hồng đậm',     'color' => '#e85c8f', 'stock' => 28],
                    ['label' => 'Đỏ tươi',      'color' => '#e53e5e', 'stock' => 25],
                    ['label' => 'Cam sành',     'color' => '#f08050', 'stock' => 30],
                    ['label' => 'Vàng nắng',    'color' => '#ffd866', 'stock' => 32],
                    ['label' => 'Xanh lá mạ',   'color' => '#a8e5c0', 'stock' => 28],
                    ['label' => 'Xanh chuối',   'color' => '#d5e87a', 'stock' => 25],
                    ['label' => 'Xanh cổ vịt',  'color' => '#4a9090', 'stock' => 22],
                    ['label' => 'Xanh biển',    'color' => '#3b7fc2', 'stock' => 26],
                    ['label' => 'Tím huế',      'color' => '#8f5cc2', 'stock' => 20],
                    ['label' => 'Nâu socola',   'color' => '#5a3828', 'stock' => 24],
                    ['label' => 'Xám chuột',    'color' => '#b0b2b8', 'stock' => 30],
                    ['label' => 'Đen',          'color' => '#1a1a20', 'stock' => 35],
                    ['label' => 'Trắng',        'color' => '#ffffff', 'stock' => 40],
                ],
                'sizes'     => ['100g'],
            ],
            [
                'slug'      => 'len-boucle-xoan-oc',
                'name'      => 'Len Bouclé Xoắn Ốc Nghệ Thuật',
                'tag'       => 'Mới',
                'price'     => 135000,
                'oldPrice'  => null,
                'image'     => '/images/4.jpg',
                'shortDesc' => 'Len bouclé texture xoắn đặc biệt — tạo hiệu ứng bông nhỏ đáng yêu.',
                'desc'      => 'Bouclé là loại len có cấu trúc xoắn vòng tự nhiên trên sợi, khi đan tạo ra mặt vải có texture như những vòng bông nhỏ. Cực kỳ thời thượng cho áo khoác và túi xách.',
                'features'  => ['Texture độc đáo', 'Không cần mẫu phức tạp', 'Phù hợp túi & áo', 'Giữ form tốt'],
                'variants'  => [
                    ['label' => 'Kem sữa',       'color' => '#f5ede0', 'stock' => 12],
                    ['label' => 'Kem café',      'color' => '#d4a574', 'stock' => 10],
                    ['label' => 'Hồng phấn',     'color' => '#f9c3d9', 'stock' => 13],
                    ['label' => 'Xanh rêu',      'color' => '#8fa878', 'stock' => 9],
                    ['label' => 'Nâu nhạt',      'color' => '#a87858', 'stock' => 11],
                    ['label' => 'Xám bạc',       'color' => '#c5c5cc', 'stock' => 14],
                    ['label' => 'Đen',           'color' => '#1a1a20', 'stock' => 8],
                ],
                'sizes'     => ['100g'],
            ],
            [
                'slug'      => 'len-chunky-dan-tay',
                'name'      => 'Len Chunky Đan Tay Siêu To',
                'tag'       => 'Hot',
                'price'     => 220000,
                'oldPrice'  => 260000,
                'image'     => '/images/3.jpg',
                'shortDesc' => 'Len super chunky 100% wool — đan chăn và khăn chỉ bằng tay không cần kim.',
                'desc'      => 'Sợi len cực dày (đường kính ~3cm) dùng để đan chăn arm-knitting. Cuộn 500g đan được chăn 80×100cm. Ấm áp và trendy, xuất hiện nhiều trên Pinterest.',
                'features'  => ['Đan bằng tay', 'Cuộn 500g', 'Wool 100%', 'Chăn hoàn thiện 4 giờ'],
                'variants'  => [
                    ['label' => 'Kem nhạt',     'color' => '#f5ede0', 'stock' => 8],
                    ['label' => 'Hồng bụi',     'color' => '#d8a8b5', 'stock' => 7],
                    ['label' => 'Xám nhạt',     'color' => '#c0c2c8', 'stock' => 10],
                    ['label' => 'Xám đậm',      'color' => '#5a5a65', 'stock' => 9],
                    ['label' => 'Xanh dusty',   'color' => '#90a5b5', 'stock' => 6],
                    ['label' => 'Nâu caramel',  'color' => '#a87858', 'stock' => 11],
                    ['label' => 'Mustard',      'color' => '#c8a038', 'stock' => 7],
                ],
                'sizes'     => ['500g', '1kg'],
            ],
            [
                'slug'      => 'len-silk-sang-trong',
                'name'      => 'Len Silk Sang Trọng',
                'tag'       => null,
                'price'     => 260000,
                'oldPrice'  => null,
                'image'     => '/images/2.jpg',
                'shortDesc' => 'Pha silk cao cấp — sợi bóng mượt, rủ đẹp cho áo vải mỏng mùa hè.',
                'desc'      => 'Hỗn hợp 50% silk + 50% cotton, sợi bóng sang trọng. Đan mặt vải rủ nhẹ, không dày, phù hợp áo cổ tròn, váy babydoll và khăn choàng cao cấp.',
                'features'  => ['Silk 50% pha cotton', 'Ánh bóng sang trọng', 'Rủ nhẹ, không dày', 'Mượt như satin'],
                'variants'  => [
                    ['label' => 'Trắng ngọc',   'color' => '#f8f4e8', 'stock' => 8],
                    ['label' => 'Hồng cánh sen','color' => '#ef87ae', 'stock' => 7],
                    ['label' => 'Xanh trứng',   'color' => '#a0d0d8', 'stock' => 6],
                    ['label' => 'Vàng kim',     'color' => '#e8c068', 'stock' => 5],
                    ['label' => 'Xám tro',      'color' => '#9ea0a8', 'stock' => 8],
                    ['label' => 'Nâu mocha',    'color' => '#8e6b4f', 'stock' => 6],
                    ['label' => 'Đen',          'color' => '#1a1a20', 'stock' => 9],
                ],
                'sizes'     => ['50g', '100g'],
            ],
        ],

        'kim-moc' => [
            [
                'slug'      => 'kim-dan-inox-9',
                'name'      => 'Bộ Kim Đan Inox 9 Cây',
                'tag'       => 'Combo',
                'price'     => 95000,
                'oldPrice'  => 125000,
                'image'     => '/images/4.jpg',
                'shortDesc' => 'Kim đan inox cao cấp, đầu nhẵn bóng, đủ size 2–6mm.',
                'desc'      => 'Bộ 9 cây kim đan inox 304 không rỉ sét, dài 35cm, đầu mài nhẵn không móc sợi. Kèm hộp cuộn vải xinh để bảo quản.',
                'features'  => ['Inox 304 không rỉ', 'Dài 35cm chuẩn', 'Đầu nhẵn không móc sợi', 'Kèm hộp đựng'],
                'variants'  => [
                    ['label' => 'Hộp hồng pastel',   'color' => '#f9c3d9', 'stock' => 20],
                    ['label' => 'Hộp xanh mint',     'color' => '#c3e8d5', 'stock' => 15],
                    ['label' => 'Hộp tím lavender',  'color' => '#d9c3e8', 'stock' => 12],
                    ['label' => 'Hộp vàng kem',      'color' => '#fbe8a9', 'stock' => 14],
                    ['label' => 'Hộp xanh baby',     'color' => '#a8d5f6', 'stock' => 11],
                ],
                'sizes'     => ['Bộ 9 cây (2–6mm)'],
            ],
            [
                'slug'      => 'moc-ergonomic-go',
                'name'      => 'Móc Ergonomic Tay Gỗ',
                'tag'       => 'Bán chạy',
                'price'     => 65000,
                'oldPrice'  => null,
                'image'     => '/images/5.jpg',
                'shortDesc' => 'Móc len tay cầm gỗ chống mỏi, đầu nhựa ABS trơn láng.',
                'desc'      => 'Thiết kế ergonomic ôm sát lòng bàn tay, thân gỗ cứng không trượt. Đầu móc mạ crôm, không gãy khi móc len dày.',
                'features'  => ['Tay cầm gỗ ergonomic', 'Đầu crôm không gãy', 'Chống mỏi tay', 'Size rõ ràng'],
                'variants'  => [
                    ['label' => 'Size 2.0mm', 'color' => '#e5d5c0', 'stock' => 15],
                    ['label' => 'Size 2.5mm', 'color' => '#e5d5c0', 'stock' => 18],
                    ['label' => 'Size 3.0mm', 'color' => '#e5d5c0', 'stock' => 22],
                    ['label' => 'Size 3.5mm', 'color' => '#e5d5c0', 'stock' => 20],
                    ['label' => 'Size 4.0mm', 'color' => '#e5d5c0', 'stock' => 15],
                    ['label' => 'Size 4.5mm', 'color' => '#e5d5c0', 'stock' => 13],
                    ['label' => 'Size 5.0mm', 'color' => '#e5d5c0', 'stock' => 12],
                    ['label' => 'Size 6.0mm', 'color' => '#e5d5c0', 'stock' => 10],
                    ['label' => 'Size 8.0mm', 'color' => '#e5d5c0', 'stock' => 8],
                ],
                'sizes'     => ['Đơn cây'],
            ],
            [
                'slug'      => 'kim-khoa-stitch-marker',
                'name'      => 'Bộ Kim Khoá & Stitch Marker',
                'tag'       => null,
                'price'     => 45000,
                'oldPrice'  => null,
                'image'     => '/images/1.jpg',
                'shortDesc' => 'Phụ kiện đánh dấu mũi đan, kẹp chỉ, kim khâu — combo đầy đủ.',
                'desc'      => 'Bộ 30 cái bao gồm: 10 stitch marker silicon, 10 kim khoá, 6 kim khâu len, 4 kéo mini. Hộp nhỏ tiện mang theo.',
                'features'  => ['Bộ 30 phụ kiện', 'Silicon không làm rách len', 'Hộp nhỏ tiện mang', 'Đủ cho 10 dự án'],
                'variants'  => [
                    ['label' => 'Hồng + trắng', 'color' => '#f9c3d9', 'stock' => 25],
                    ['label' => 'Xanh + trắng', 'color' => '#c3e8d5', 'stock' => 20],
                    ['label' => 'Tím + trắng',  'color' => '#d9c3e8', 'stock' => 18],
                    ['label' => 'Vàng + trắng', 'color' => '#fbe8a9', 'stock' => 22],
                ],
                'sizes'     => ['Combo 30 món'],
            ],
            [
                'slug'      => 'kim-dan-tron-day-cap',
                'name'      => 'Kim Đan Tròn Dây Cáp',
                'tag'       => 'Mới',
                'price'     => 85000,
                'oldPrice'  => null,
                'image'     => '/images/3.jpg',
                'shortDesc' => 'Kim đan tròn nối cáp mềm — đan áo liền không có đường ráp.',
                'desc'      => 'Kim đan tròn inox nối bằng cáp silicone mềm dẻo, không rối sợi. Đan được mọi loại áo liền, chăn lớn, mũ không đường may.',
                'features'  => ['Cáp silicone mềm', 'Đầu inox 304', 'Đan áo liền', 'Xoay 360°'],
                'variants'  => [
                    ['label' => 'Size 3.0mm', 'color' => '#e5d5c0', 'stock' => 14],
                    ['label' => 'Size 3.5mm', 'color' => '#e5d5c0', 'stock' => 16],
                    ['label' => 'Size 4.0mm', 'color' => '#e5d5c0', 'stock' => 18],
                    ['label' => 'Size 4.5mm', 'color' => '#e5d5c0', 'stock' => 15],
                    ['label' => 'Size 5.0mm', 'color' => '#e5d5c0', 'stock' => 12],
                    ['label' => 'Size 6.0mm', 'color' => '#e5d5c0', 'stock' => 10],
                ],
                'sizes'     => ['Dây 40cm', 'Dây 60cm', 'Dây 80cm', 'Dây 100cm'],
            ],
            [
                'slug'      => 'moc-bamboo-tu-nhien',
                'name'      => 'Móc Tre Bamboo Tự Nhiên',
                'tag'       => 'Eco',
                'price'     => 55000,
                'oldPrice'  => null,
                'image'     => '/images/6.jpg',
                'shortDesc' => 'Móc tre vân gỗ tự nhiên, nhẹ tay — thân thiện môi trường.',
                'desc'      => 'Tre Việt Nam đánh nhẵn, sơn bóng không độc hại. Nhẹ hơn móc inox, ấm tay khi cầm lâu. Sản xuất thủ công tại làng nghề Hà Nam.',
                'features'  => ['Tre 100% tự nhiên', 'Siêu nhẹ', 'Ấm tay mùa đông', 'Thủ công Việt Nam'],
                'variants'  => [
                    ['label' => 'Size 2.5mm', 'color' => '#d4a574', 'stock' => 12],
                    ['label' => 'Size 3.0mm', 'color' => '#d4a574', 'stock' => 14],
                    ['label' => 'Size 3.5mm', 'color' => '#d4a574', 'stock' => 16],
                    ['label' => 'Size 4.0mm', 'color' => '#d4a574', 'stock' => 15],
                    ['label' => 'Size 5.0mm', 'color' => '#d4a574', 'stock' => 10],
                    ['label' => 'Size 6.0mm', 'color' => '#d4a574', 'stock' => 8],
                    ['label' => 'Bộ 6 size',  'color' => '#d4a574', 'stock' => 6],
                ],
                'sizes'     => ['Đơn cây', 'Bộ 6 cây'],
            ],
            [
                'slug'      => 'kim-giu-mui-cable',
                'name'      => 'Kim Giữ Mũi Cable Knitting',
                'tag'       => null,
                'price'     => 38000,
                'oldPrice'  => null,
                'image'     => '/images/2.jpg',
                'shortDesc' => 'Kim giữ mũi chữ U để đan hoa văn cable — không bị tuột mũi.',
                'desc'      => 'Bộ 3 cây kim chữ U bằng nhựa ABS bền. Dùng để giữ mũi khi đan hoa văn twisted, bím tóc, cable trên áo len.',
                'features'  => ['Nhựa ABS bền', '3 size: S M L', 'Không tuột mũi', 'Nhỏ gọn'],
                'variants'  => [
                    ['label' => 'Hồng',  'color' => '#f9c3d9', 'stock' => 20],
                    ['label' => 'Xanh',  'color' => '#c3e8d5', 'stock' => 18],
                    ['label' => 'Tím',   'color' => '#d9c3e8', 'stock' => 15],
                    ['label' => 'Vàng',  'color' => '#fbe8a9', 'stock' => 16],
                ],
                'sizes'     => ['Bộ 3 cây'],
            ],
        ],

        'starter-kit' => [
            [
                'slug'      => 'kit-gau-bong',
                'name'      => 'Starter Kit Thú Bông Gấu',
                'tag'       => 'Sale',
                'price'     => 210000,
                'oldPrice'  => 280000,
                'image'     => '/images/5.jpg',
                'shortDesc' => 'Bộ kit đầy đủ len, kim, mắt thú và hướng dẫn móc gấu bông.',
                'desc'      => 'Kit bao gồm: 3 cuộn len cotton 50g, 1 móc 3mm, 2 mắt thú 9mm, bông gòn, kim khâu, kéo mini, sách hướng dẫn 24 trang có hình minh hoạ. Hoàn thành 1 gấu cao ~18cm trong 4 giờ.',
                'features'  => ['Đầy đủ nguyên liệu', 'Hướng dẫn từng bước', 'Phù hợp người mới', 'Thành phẩm 18cm'],
                'variants'  => [
                    ['label' => 'Gấu nâu cổ điển',   'color' => '#a87858', 'stock' => 12],
                    ['label' => 'Gấu trắng kem',     'color' => '#e5d5c0', 'stock' => 10],
                    ['label' => 'Gấu hồng pastel',   'color' => '#f9c3d9', 'stock' => 15],
                    ['label' => 'Gấu xám bạc',       'color' => '#c0c2c8', 'stock' => 9],
                    ['label' => 'Gấu mật ong',       'color' => '#e8c068', 'stock' => 11],
                    ['label' => 'Gấu đen huyền',     'color' => '#2a2a33', 'stock' => 8],
                ],
                'sizes'     => ['Combo đầy đủ'],
            ],
            [
                'slug'      => 'kit-khan-basic',
                'name'      => 'Starter Kit Khăn Quàng Basic',
                'tag'       => 'Mới',
                'price'     => 180000,
                'oldPrice'  => null,
                'image'     => '/images/3.jpg',
                'shortDesc' => 'Combo len + kim cho người mới, móc 1 khăn quàng trong tuần.',
                'desc'      => 'Kit bao gồm: 4 cuộn len acrylic mềm, 1 bộ kim 5mm, sách hướng dẫn đan mũi cơ bản 16 trang. Thành phẩm khăn 150×20cm.',
                'features'  => ['Len mềm cho da nhạy', 'Kim size chuẩn cho beginner', 'Sách hướng dẫn tiếng Việt', 'Thành phẩm 150cm'],
                'variants'  => [
                    ['label' => 'Tone pastel',    'color' => 'linear-gradient(135deg,#f9c3d9,#c3e8d5)', 'stock' => 20],
                    ['label' => 'Tone đất',       'color' => 'linear-gradient(135deg,#d89878,#8f4756)', 'stock' => 15],
                    ['label' => 'Tone xanh',      'color' => 'linear-gradient(135deg,#2c3e60,#a8d5d5)', 'stock' => 18],
                    ['label' => 'Tone sunset',    'color' => 'linear-gradient(135deg,#ff9a70,#f6a8c5)', 'stock' => 14],
                    ['label' => 'Tone monochrome','color' => 'linear-gradient(135deg,#1a1a20,#c0c2c8)', 'stock' => 12],
                    ['label' => 'Tone candy',     'color' => 'linear-gradient(135deg,#ffd1dc,#d9c3e8)', 'stock' => 16],
                ],
                'sizes'     => ['Combo đầy đủ'],
            ],
            [
                'slug'      => 'kit-amigurumi-hoa',
                'name'      => 'Starter Kit Amigurumi Bó Hoa Mini',
                'tag'       => 'Hot',
                'price'     => 245000,
                'oldPrice'  => 295000,
                'image'     => '/images/2.jpg',
                'shortDesc' => 'Tự móc bó hoa amigurumi — quà tặng độc đáo, không bao giờ héo.',
                'desc'      => 'Kit móc 5 bông hoa mini (hồng, tulip, daisy, sunflower, tú cầu) + lá + thân dây kẽm. Bao gồm len cotton 20 màu mini, móc 2.5mm, kim khâu, hướng dẫn chi tiết.',
                'features'  => ['Móc được 5 loại hoa', '20 màu len mini', 'Quà tặng ý nghĩa', 'Dây kẽm uốn dễ'],
                'variants'  => [
                    ['label' => 'Bó hoa pastel',  'color' => 'linear-gradient(135deg,#f9c3d9,#fbe8a9,#c3e8d5)', 'stock' => 15],
                    ['label' => 'Bó hoa đỏ lãng mạn', 'color' => 'linear-gradient(135deg,#e53e5e,#8f4756)', 'stock' => 12],
                    ['label' => 'Bó hoa trắng tinh khôi', 'color' => '#fafafa', 'stock' => 10],
                    ['label' => 'Bó hoa vintage',  'color' => 'linear-gradient(135deg,#d89878,#a87858)', 'stock' => 11],
                ],
                'sizes'     => ['Combo 5 bông', 'Combo 10 bông'],
            ],
            [
                'slug'      => 'kit-tui-tote-trendy',
                'name'      => 'Starter Kit Túi Tote Móc Trendy',
                'tag'       => 'Mới',
                'price'     => 195000,
                'oldPrice'  => null,
                'image'     => '/images/4.jpg',
                'shortDesc' => 'Móc túi tote handmade cá tính, đi shopping hay đi học đều hợp.',
                'desc'      => 'Kit bao gồm: 3 cuộn len cotton dày 100g, 1 móc 5mm, bộ sticker iron-on, dây đeo vai. Thành phẩm túi 35×40cm.',
                'features'  => ['Len dày bền bỉ', 'Thành phẩm 35×40cm', 'Sticker tuỳ chỉnh', 'Đeo vai thoải mái'],
                'variants'  => [
                    ['label' => 'Trắng + viền đen',   'color' => 'linear-gradient(135deg,#ffffff,#1a1a20)', 'stock' => 18],
                    ['label' => 'Hồng + viền trắng',  'color' => 'linear-gradient(135deg,#f9c3d9,#ffffff)', 'stock' => 16],
                    ['label' => 'Beige + viền kem',   'color' => 'linear-gradient(135deg,#f5ede0,#d4a574)', 'stock' => 14],
                    ['label' => 'Xanh navy + trắng',  'color' => 'linear-gradient(135deg,#2c3e60,#ffffff)', 'stock' => 12],
                    ['label' => 'Đen + viền hồng',    'color' => 'linear-gradient(135deg,#1a1a20,#f9c3d9)', 'stock' => 15],
                ],
                'sizes'     => ['Combo đầy đủ'],
            ],
            [
                'slug'      => 'kit-mu-beanie-winter',
                'name'      => 'Starter Kit Mũ Beanie Mùa Đông',
                'tag'       => 'Hot',
                'price'     => 165000,
                'oldPrice'  => 195000,
                'image'     => '/images/6.jpg',
                'shortDesc' => 'Tự đan mũ beanie ấm áp cho mùa đông, kèm pompom cute.',
                'desc'      => 'Kit gồm: 2 cuộn len wool 100g, 1 kim đan tròn 5mm, pompom lông gắn sẵn, sách hướng dẫn 12 trang. Thành phẩm 1 mũ size unisex.',
                'features'  => ['Wool ấm cho mùa đông', 'Pompom cute tuỳ chọn', 'Fits unisex', 'Thành phẩm trong 3 giờ'],
                'variants'  => [
                    ['label' => 'Mũ kem + pompom trắng',  'color' => 'linear-gradient(135deg,#f5ede0,#ffffff)', 'stock' => 14],
                    ['label' => 'Mũ hồng + pompom trắng', 'color' => 'linear-gradient(135deg,#f9c3d9,#ffffff)', 'stock' => 16],
                    ['label' => 'Mũ xám + pompom đen',    'color' => 'linear-gradient(135deg,#9fa0a5,#1a1a20)', 'stock' => 12],
                    ['label' => 'Mũ nâu + pompom kem',    'color' => 'linear-gradient(135deg,#a87858,#f5ede0)', 'stock' => 10],
                    ['label' => 'Mũ đen + pompom hồng',   'color' => 'linear-gradient(135deg,#1a1a20,#f9c3d9)', 'stock' => 13],
                ],
                'sizes'     => ['Size unisex', 'Size trẻ em'],
            ],
        ],

        'phu-kien' => [
            [
                'slug'      => 'mat-thu-an-toan',
                'name'      => 'Mắt Thú An Toàn Set 20 Cặp',
                'tag'       => null,
                'price'     => 55000,
                'oldPrice'  => null,
                'image'     => '/images/6.jpg',
                'shortDesc' => 'Mắt thú nhựa an toàn, khoá chặt sau lưng — đủ size cho mọi loại thú bông.',
                'desc'      => 'Set 20 cặp mắt thú với 5 size khác nhau (6/8/10/12/15mm). Nhựa ABS không độc, khoá chặt sau lưng không rớt. An toàn cho bé trên 3 tuổi.',
                'features'  => ['20 cặp đủ size', 'Nhựa ABS an toàn', 'Khoá chặt không rớt', 'Phù hợp thú bông'],
                'variants'  => [
                    ['label' => 'Đen',         'color' => '#2a2a33', 'stock' => 30],
                    ['label' => 'Nâu',         'color' => '#6a4a3a', 'stock' => 25],
                    ['label' => 'Xanh biển',   'color' => '#2c5580', 'stock' => 18],
                    ['label' => 'Xanh lá',     'color' => '#4a9058', 'stock' => 15],
                    ['label' => 'Hổ phách',    'color' => '#b88038', 'stock' => 16],
                    ['label' => 'Tím',         'color' => '#8050a0', 'stock' => 12],
                    ['label' => 'Mix 7 màu',   'color' => 'linear-gradient(135deg,#2a2a33,#6a4a3a,#2c5580)', 'stock' => 22],
                ],
                'sizes'     => ['Set 20 cặp', 'Set 50 cặp'],
            ],
            [
                'slug'      => 'tui-dung-len',
                'name'      => 'Túi Đựng Len Canvas',
                'tag'       => 'Mới',
                'price'     => 75000,
                'oldPrice'  => null,
                'image'     => '/images/4.jpg',
                'shortDesc' => 'Túi vải canvas đựng len khi đan — chống rối sợi, có khoá kéo.',
                'desc'      => 'Túi canvas in hoạ tiết yarn ball xinh xắn, có ngăn chống sợi rối khi đang đan di chuyển. Dung tích đựng 2-3 cuộn len 100g.',
                'features'  => ['Canvas dày không rách', 'Chống sợi rối khi di chuyển', 'Có quai đeo vai', 'Hoạ tiết handmade xinh'],
                'variants'  => [
                    ['label' => 'Hồng nhạt',    'color' => '#fde0ee', 'stock' => 15],
                    ['label' => 'Hồng đậm',     'color' => '#e85c8f', 'stock' => 13],
                    ['label' => 'Trắng kem',    'color' => '#f5ede0', 'stock' => 20],
                    ['label' => 'Xanh biển',    'color' => '#a8d5d5', 'stock' => 12],
                    ['label' => 'Xanh mint',    'color' => '#c3e8d5', 'stock' => 11],
                    ['label' => 'Tím lavender', 'color' => '#d9c3e8', 'stock' => 10],
                    ['label' => 'Đen',          'color' => '#1a1a20', 'stock' => 18],
                ],
                'sizes'     => ['Size S', 'Size M (đựng 2-3 cuộn)', 'Size L (đựng 5-6 cuộn)'],
            ],
            [
                'slug'      => 'khoa-tui-kim-loai',
                'name'      => 'Khoá Túi Kim Loại Vintage',
                'tag'       => null,
                'price'     => 42000,
                'oldPrice'  => null,
                'image'     => '/images/1.jpg',
                'shortDesc' => 'Khoá cài kim loại vintage — hoàn thiện túi handmade chuyên nghiệp.',
                'desc'      => 'Bộ 5 khoá kim loại mạ cao cấp dành cho túi móc/đan. Nhiều kiểu dáng: chữ D, xoay, lock, magnet. Dùng kim khâu len gắn lên viền túi.',
                'features'  => ['Bộ 5 khoá', 'Mạ không gỉ', 'Nhiều kiểu dáng', 'Dễ gắn lên túi'],
                'variants'  => [
                    ['label' => 'Vàng đồng',    'color' => '#c8a040', 'stock' => 20],
                    ['label' => 'Bạc sáng',     'color' => '#c8c8d0', 'stock' => 18],
                    ['label' => 'Đen matte',    'color' => '#2a2a33', 'stock' => 15],
                    ['label' => 'Vàng hồng',    'color' => '#d8a098', 'stock' => 12],
                ],
                'sizes'     => ['Bộ 5 chiếc'],
            ],
            [
                'slug'      => 'sticker-iron-on',
                'name'      => 'Sticker Iron-On Cute',
                'tag'       => 'Hot',
                'price'     => 35000,
                'oldPrice'  => 50000,
                'image'     => '/images/3.jpg',
                'shortDesc' => 'Miếng dán ủi nhiệt — decorate túi tote, áo len handmade.',
                'desc'      => 'Set 10 sticker với hoạ tiết cute (hoa, trái cây, cat, dinosaur...). Dùng bàn ủi gia nhiệt 180°C trong 10s là dán chắc. Giặt máy không bong.',
                'features'  => ['Set 10 sticker', 'Ủi là dán', 'Giặt không bong', 'Hoạ tiết đa dạng'],
                'variants'  => [
                    ['label' => 'Bộ Hoa lá',       'color' => 'linear-gradient(135deg,#f9c3d9,#c3e8d5)', 'stock' => 25],
                    ['label' => 'Bộ Trái cây',     'color' => 'linear-gradient(135deg,#ff9a70,#fbe8a9)', 'stock' => 22],
                    ['label' => 'Bộ Động vật',     'color' => 'linear-gradient(135deg,#a87858,#e5d5c0)', 'stock' => 20],
                    ['label' => 'Bộ Vũ trụ',       'color' => 'linear-gradient(135deg,#2c3e60,#c5a8e0)', 'stock' => 18],
                    ['label' => 'Bộ Chữ cái ABC',  'color' => 'linear-gradient(135deg,#1a1a20,#ffffff)', 'stock' => 30],
                    ['label' => 'Bộ Emoji',        'color' => '#ffd866', 'stock' => 28],
                ],
                'sizes'     => ['Set 10 cái', 'Set 20 cái'],
            ],
            [
                'slug'      => 'day-quai-tui-da',
                'name'      => 'Dây Quai Túi Da Cao Cấp',
                'tag'       => null,
                'price'     => 85000,
                'oldPrice'  => null,
                'image'     => '/images/5.jpg',
                'shortDesc' => 'Dây quai da thật dành cho túi móc — nâng cấp thành túi sang trọng.',
                'desc'      => 'Da thật Ý, khoen kim loại mạ vàng hồng, dài 120cm có thể điều chỉnh. Gắn vào túi móc để hoàn thiện túi handmade đẳng cấp boutique.',
                'features'  => ['Da thật Ý', 'Khoen mạ vàng hồng', 'Dài 120cm điều chỉnh', 'Bền 5+ năm'],
                'variants'  => [
                    ['label' => 'Nâu cognac',  'color' => '#8b4a30', 'stock' => 14],
                    ['label' => 'Nâu caramel', 'color' => '#b8784a', 'stock' => 12],
                    ['label' => 'Đen',         'color' => '#1a1a20', 'stock' => 18],
                    ['label' => 'Kem ngà',     'color' => '#e8d8b8', 'stock' => 10],
                    ['label' => 'Đỏ rượu',     'color' => '#6b2e3e', 'stock' => 9],
                    ['label' => 'Hồng baby',   'color' => '#ffd1dc', 'stock' => 11],
                ],
                'sizes'     => ['Bản 1cm', 'Bản 2cm', 'Bản 3cm'],
            ],
            [
                'slug'      => 'bong-gon-polyester',
                'name'      => 'Bông Gòn Polyester Cao Cấp',
                'tag'       => null,
                'price'     => 48000,
                'oldPrice'  => null,
                'image'     => '/images/2.jpg',
                'shortDesc' => 'Bông nhồi thú bông — mềm, đàn hồi tốt, không vón cục.',
                'desc'      => 'Polyester cao cấp siêu mịn, không vón sau khi nhồi, giữ form thú bông hoàn hảo. Túi 500g nhồi được 3-4 thú bông cỡ vừa.',
                'features'  => ['Polyester cao cấp', 'Không vón cục', '500g/túi', 'Đàn hồi tốt'],
                'variants'  => [
                    ['label' => 'Trắng tinh',  'color' => '#ffffff', 'stock' => 40],
                    ['label' => 'Kem',         'color' => '#f5ede0', 'stock' => 30],
                ],
                'sizes'     => ['500g', '1kg'],
            ],
        ],
    ],
];
